---
title: "j-ctox-dp"
author: "Claudio Zanettini"
editor: source
date: '`r Sys.Date()`'
format:
  html:
    self_contained: true
    embed-resources: true
    toc: true
    toc-depth: 3
    page-layout: full
---

```{r echo=FALSE}
# https://gist.github.com/debruine/01b4ce274733a4a99622365e8c6df701
# custom knit_print functions for data.frame
library(knitr)
# print everything as paged ----
# knit_print.data.frame <- function (x, options, ...) {
#   rmarkdown::paged_table(x, options) |>
#     rmarkdown:::print.paged_df()
# }
# registerS3method("knit_print", "data.frame", knit_print.data.frame)
# print everything as kable ----
# knit_print.data.frame <- function (x, options, ...) {
#   knitr::kable(x) |> knitr::knit_print(options, ...)
# }
# registerS3method("knit_print", "data.frame", knit_print.data.frame)
# super-customised table printing ----
`%||%` <- function(l, r) {
  if (is.null(l)) r else l
}
knit_print.data.frame <- function(x, options, ...) {
  # get options
  digits <- options$digits %||% getOption("digits")
  rownames <- options$rownames %||% FALSE
  pageLength <- options$pageLength %||% 10
  escape <- options$escape %||% TRUE
  caption <- options$fig.cap

  # remove caption so it doesn't print twice (NOT WORKING)
  options$fig.cap <- NULL

  # use DT for longer tables in html
  if (nrow(x) > pageLength & knitr::is_html_output()) {
    numeric_cols <- sapply(x, is.numeric) |>
      which() |>
      names()
    dt <- DT::datatable(x,
      rownames = rownames,
      caption = caption,
      escape = escape,
      width = "100%",
      height = "auto",
      options = list(pageLength = 5),
      selection = "none",
      filter = "top"
    )
    if (length(numeric_cols) > 0) {
      dt <- DT::formatRound(dt,
        columns = numeric_cols,
        digits = digits,
      )
    }
    knitr::knit_print(dt, options)
  } else {
    # use kableExtra::kable for PDFs or shorter tables
    k <- kableExtra::kable(x,
      digits = digits,
      row.names = rownames,
      caption = caption,
      escape = escape
    ) |>
      kableExtra::kable_styling(
        full_width = options$full_width,
        bootstrap_options = c("striped", "hover")
      )

    if (knitr::is_html_output()) {
      k <- c("<div class=\"kable-table\">", k, "</div>") |>
        paste(collapse = "\n")
    }

    knitr::asis_output(k)
  }
}
registerS3method("knit_print", "data.frame", knit_print.data.frame)
```

```{=html}
<style>
.output {
  border: 1px solid #dcdcdc;
  background-color: #e6f2ff;
  padding: 10px;
  margin: 10px 0;
  border-radius: 5px;
}
</style>
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
targets::tar_load_globals(script = here::here("_targets.R"))
theme_set(theme_bw())
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
tar_config_set(store = here("_targets"))
```

```{r}
tar_load(orange_chem_all)
```

```{r}
orange_chem_all
orange_chem_all$MolecularWeight
```

```{r}
tar_load(solution)

solution$MolecularWeight
```

